[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "character_sheet_parser"
path = "src/lib.rs"

[[bin]]
name = "character_sheet_parser_cli"
path = "src/bin/bin.rs"

[dependencies]
regex = "1.10.3"
text_io = "0.1.12"
thiserror = "1.0.57"
